- name: Update Linux Server
  hosts: 127.0.0.1  # Replace with your server group or hostname
  become: yes  # If you need to escalate privileges with sudo
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Run df command to check storage
      command: df -h
      register: df_output

    - debug:
        var: df_output.stdout_lines


    - name: Send ntfy.sh update
      uri:
        url: "https://ntfy.sh/harleyfretwell01"
        method: POST
        body: "Storage Check Done!"
