- name: Update Linux Server
  hosts: 127.0.0.1  # Replace with your server group or hostname
  become: yes  # If you need to escalate privileges with sudo
  vars:
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes   # For Ubuntu/Debian
      when: ansible_os_family == 'Debian'

    - name: Update package cache
      yum:
        name: '*'
        state: latest       # For CentOS/RHEL
      when: ansible_os_family == 'RedHat'

    - name: Upgrade all packages
      apt:
        upgrade: dist       # For Ubuntu/Debian
      when: ansible_os_family == 'Debian'

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest       # For CentOS/RHEL
      when: ansible_os_family == 'RedHat'

    - name: Clean up package cache
      apt:
        autoclean: yes      # For Ubuntu/Debian
      when: ansible_os_family == 'Debian'

    - name: Run apt-get autoclean with sudo
      command: sudo apt-get autoclean
