
- name: Check Storage on Windows Host
  hosts: all
  gather_facts: no
  tasks:
    - name: Get storage information
      win_shell: Get-PSDrive -PSProvider FileSystem | Select-Object Name, Used, Free, @{Name='TotalSize';Expression={$_.Used + $_.Free}} | Format-Table -AutoSize
      register: storage_info

    - name: Print storage information
      debug:
        msg: "{{ storage_info.stdout_lines }}"
