---
- name: Check Storage on Windows Host via SSH
  hosts: windows
  gather_facts: no
  tasks:
    - name: Get storage information
      command: powershell.exe -Command "Get-PSDrive -PSProvider FileSystem | Select-Object Name, Used, Free, @{Name='TotalSize';Expression={\$_.Used + \$_.Free}} | Format-Table -AutoSize"
      register: storage_info

    - name: Print storage information
      debug:
        msg: "{{ storage_info.stdout_lines }}"
