- name: Start an Ubuntu container in Docker with a random name
  hosts: localhost  # You can specify the target host or hosts here
  become: yes  # Optionally, if you need to run Docker commands with sudo

  tasks:
    - name: Generate a random container name
      command: python -c "import random, string; print(''.join(random.choice(string.ascii_lowercase + string.digits) for _ in range(10)))"
      register: random_container_name
      changed_when: false

    - name: Pull the Ubuntu image from Docker Hub
      docker_image:
        name: ubuntu:latest

    - name: Start the Ubuntu container
      docker_container:
        name: "{{ random_container_name.stdout }}"
        image: ubuntu:latest
        state: started

    - name: Send ntfy.sh update with total storage
      uri:
        url: "https://ntfy.sh/harleyfretwell01"
        method: POST
        body: "Docker Container {{random_container_name}} has been spun up!"
